# Generated by Django 4.2.5 on 2023-09-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sortname', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('phoneCode', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lat', models.CharField(max_length=250, verbose_name='Latitude')),
                ('lng', models.CharField(max_length=250, verbose_name='Longitude')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
