# Generated by Django 4.2.5 on 2023-09-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_remove_city_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.city')),
                ('state_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.state')),
            ],
        ),
    ]
