# Generated by Django 4.2.5 on 2023-09-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_statecity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statecity',
            options={'verbose_name_plural': 'State Code'},
        ),
    ]
