# Generated by Django 4.2.5 on 2023-09-18 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(default=uuid.UUID('aa6c97f3-1fe7-4b4d-a03b-b42da861decf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
